### ISSUE TITLE
Socket buffer size error on startup

### ISSUE THREAD

**Issue by fer-rum** [Homer-Conferencing/Homer-Conferencing#66]
Hi there,

When starting Homer (Beta 0.25.0), I get several errors on the console:

```
(14:20.26) ERROR:   Homer::Base::Socket(920): Socket 22 reports 524284 bytes as receive buffer size, which differs from the expected 262142 bytes
(14:20.26) ERROR:   Homer::Base::Socket(874): Socket 22 reports 425984 bytes as send buffer size, which differs from the expected 262142 bytes
(14:20.27) ERROR:   Homer::Base::Socket(920): Socket 23 reports 524284 bytes as receive buffer size, which differs from the expected 262142 bytes
(14:20.27) ERROR:   Homer::Base::Socket(874): Socket 23 reports 425984 bytes as send buffer size, which differs from the expected 262142 bytes
```

While chatting works fine, audio and video transmissions do not work at all. (This may also be a firewall problem, so I can not blame it on the errors above yet.)

My system is a (X)ubuntu 14.04 LTS with kernel

```
Linux 3.13.0-51-generic x86_64 GNU/Linux
```

I tried to manually adapt the systems socket buffer sizes, but to no avail.
Also, trying a complete rebuild did solve nothing.

**Follow-up questions:**
What are port 22 (ssh) and 23 (telnet) used for by Homer?
Is it really an error, if the buffer is larger then expected? 

Thanks in advance. :)

**Comment by ThomasVolkert** [comment]
Hi, these outputs are quite misleadung and are already removed in the current source code. You could try RC2 of version 0.26: http://sourceforge.net/projects/homer-conf/files/releases/Homer%200.26.0/rc2/Homer-Conferencing.exe/download
Ports 22 and 23 are not used by Homer. The numbers you see are the file numbers.

Have you figured out if your A/V problems were caused by your firewall or not?

BR,Thomas.
